DROP TABLE IF EXISTS quiz_data;

CREATE TABLE quiz_data (
    id PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    question TEXT NOT NULL UNIQUE,
    candidate_answers TEXT [] NOT NULL,
    correct_answer TEXT NOT NULL,
    tags TEXT[] NOT NULL
);